export interface Tool {
  id: string;
  name: string;
  description: string;
  path: string;
  category: string;
  subcategory: string;
  keywords: string[];
}

export interface Subcategory {
  id: string;
  name: string;
  description: string;
  path: string;
  icon: string;
}

export interface Category {
  id: string;
  name: string;
  description: string;
  path: string;
  subcategories: Subcategory[];
}

export const CATEGORIES: Record<string, Category> = {
  'dev-tools': {
    id: 'dev-tools',
    name: 'Developer Tools',
    description: 'Essential tools for developers - JSON, JWT, Regex, and code utilities',
    path: '/dev-tools',
    subcategories: [
      {
        id: 'json-tools',
        name: 'JSON Tools',
        description: 'JSON formatting, validation, and conversion tools',
        path: '/dev-tools/json-tools',
        icon: '{ }',
      },
      {
        id: 'jwt-security',
        name: 'JWT & Security',
        description: 'JWT decoding, hashing, and security utilities',
        path: '/dev-tools/jwt-security',
        icon: '🔐',
      },
      {
        id: 'regex-tools',
        name: 'Regex Tools',
        description: 'Regular expression testing, generation, and utilities',
        path: '/dev-tools/regex-tools',
        icon: '.*',
      },
      {
        id: 'code-utilities',
        name: 'Code Utilities',
        description: 'HTML, CSS, and JavaScript minifiers and formatters',
        path: '/dev-tools/code-utilities',
        icon: '</>',
      },
    ],
  },
  'seo-marketing': {
    id: 'seo-marketing',
    name: 'SEO & Marketing Tools',
    description: 'SEO optimization, meta tags, UTM tracking, and content analysis tools',
    path: '/seo-marketing',
    subcategories: [
      {
        id: 'meta-serp',
        name: 'Meta & SERP Tools',
        description: 'Meta tags, SERP previews, and social media card generators',
        path: '/seo-marketing/meta-serp',
        icon: '🔍',
      },
      {
        id: 'robots-indexing',
        name: 'Robots & Indexing',
        description: 'Robots.txt, sitemaps, and indexing control tools',
        path: '/seo-marketing/robots-indexing',
        icon: '🤖',
      },
      {
        id: 'utm-campaign',
        name: 'UTM & Campaign Tools',
        description: 'UTM builders, campaign tracking, and analytics tools',
        path: '/seo-marketing/utm-campaign',
        icon: '📊',
      },
      {
        id: 'content-writing',
        name: 'Content & Writing',
        description: 'Readability, keyword density, and text analysis tools',
        path: '/seo-marketing/content-writing',
        icon: '✍️',
      },
    ],
  },
  'calculators': {
    id: 'calculators',
    name: 'Calculators',
    description: 'Business, tech, SEO, and general purpose calculators for developers and marketers',
    path: '/calculators',
    subcategories: [
      {
        id: 'saas-startup',
        name: 'SaaS & Startup',
        description: 'MRR, ARR, churn, CAC, LTV, and revenue calculators',
        path: '/calculators/saas-startup',
        icon: '💰',
      },
      {
        id: 'tech-hosting',
        name: 'Tech & Hosting',
        description: 'File size, bandwidth, CDN, and hosting cost calculators',
        path: '/calculators/tech-hosting',
        icon: '🖥️',
      },
      {
        id: 'seo-calc',
        name: 'SEO Calculators',
        description: 'Keyword density, title width, backlink value calculators',
        path: '/calculators/seo-calc',
        icon: '📈',
      },
      {
        id: 'general-utils',
        name: 'General Utilities',
        description: 'Percentage, time, unit, age, and currency calculators',
        path: '/calculators/general-utils',
        icon: '🧮',
      },
    ],
  },
  'design-tools': {
    id: 'design-tools',
    name: 'UI/UX Design Tools',
    description: 'Color tools, palette generators, and design utilities for designers and developers',
    path: '/design-tools',
    subcategories: [
      {
        id: 'color-tools',
        name: 'Color Tools',
        description: 'Palette generators, color converters, and accessibility checkers',
        path: '/design-tools/color-tools',
        icon: '🎨',
      },
    ],
  },
};

export const TOOLS: Tool[] = [
  {
    id: 'json-to-yaml',
    name: 'JSON to YAML Converter',
    description: 'Convert JSON data to YAML format instantly',
    path: '/dev-tools/json-tools/json-to-yaml',
    category: 'dev-tools',
    subcategory: 'json-tools',
    keywords: ['json', 'yaml', 'convert', 'converter', 'transform'],
  },
  {
    id: 'yaml-to-json',
    name: 'YAML to JSON Converter',
    description: 'Convert YAML data to JSON format instantly',
    path: '/dev-tools/json-tools/yaml-to-json',
    category: 'dev-tools',
    subcategory: 'json-tools',
    keywords: ['yaml', 'json', 'convert', 'converter', 'transform'],
  },
  {
    id: 'json-to-toml',
    name: 'JSON to TOML Converter',
    description: 'Convert JSON data to TOML format',
    path: '/dev-tools/json-tools/json-to-toml',
    category: 'dev-tools',
    subcategory: 'json-tools',
    keywords: ['json', 'toml', 'convert', 'converter', 'transform'],
  },
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format and prettify JSON with syntax highlighting',
    path: '/dev-tools/json-tools/json-formatter',
    category: 'dev-tools',
    subcategory: 'json-tools',
    keywords: ['json', 'format', 'prettify', 'beautify', 'indent'],
  },
  {
    id: 'json-minifier',
    name: 'JSON Minifier',
    description: 'Minify JSON by removing whitespace and formatting',
    path: '/dev-tools/json-tools/json-minifier',
    category: 'dev-tools',
    subcategory: 'json-tools',
    keywords: ['json', 'minify', 'compress', 'compact'],
  },
  {
    id: 'json-validator',
    name: 'JSON Validator',
    description: 'Validate JSON syntax and structure',
    path: '/dev-tools/json-tools/json-validator',
    category: 'dev-tools',
    subcategory: 'json-tools',
    keywords: ['json', 'validate', 'validation', 'check', 'syntax'],
  },
  {
    id: 'csv-to-json',
    name: 'CSV to JSON Converter',
    description: 'Convert CSV data to JSON format',
    path: '/dev-tools/json-tools/csv-to-json',
    category: 'dev-tools',
    subcategory: 'json-tools',
    keywords: ['csv', 'json', 'convert', 'converter', 'spreadsheet'],
  },
  {
    id: 'json-diff',
    name: 'JSON Diff Checker',
    description: 'Compare two JSON objects and find differences',
    path: '/dev-tools/json-tools/json-diff',
    category: 'dev-tools',
    subcategory: 'json-tools',
    keywords: ['json', 'diff', 'compare', 'difference', 'check'],
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode and inspect JWT tokens offline',
    path: '/dev-tools/jwt-security/jwt-decoder',
    category: 'dev-tools',
    subcategory: 'jwt-security',
    keywords: ['jwt', 'decode', 'token', 'authentication', 'security'],
  },
  {
    id: 'jwt-expiry-checker',
    name: 'JWT Expiry Checker',
    description: 'Check JWT token expiration time',
    path: '/dev-tools/jwt-security/jwt-expiry-checker',
    category: 'dev-tools',
    subcategory: 'jwt-security',
    keywords: ['jwt', 'expiry', 'expiration', 'token', 'check'],
  },
  {
    id: 'base64-encode-decode',
    name: 'Base64 Encode/Decode',
    description: 'Encode and decode Base64 strings',
    path: '/dev-tools/jwt-security/base64-encode-decode',
    category: 'dev-tools',
    subcategory: 'jwt-security',
    keywords: ['base64', 'encode', 'decode', 'encoding', 'decoding'],
  },
  {
    id: 'sha256-hash',
    name: 'SHA256 Hash Generator',
    description: 'Generate SHA256 hash from text',
    path: '/dev-tools/jwt-security/sha256-hash',
    category: 'dev-tools',
    subcategory: 'jwt-security',
    keywords: ['sha256', 'hash', 'checksum', 'crypto', 'security'],
  },
  {
    id: 'md5-hash',
    name: 'MD5 Hash Generator',
    description: 'Generate MD5 hash from text',
    path: '/dev-tools/jwt-security/md5-hash',
    category: 'dev-tools',
    subcategory: 'jwt-security',
    keywords: ['md5', 'hash', 'checksum', 'crypto'],
  },
  {
    id: 'password-strength',
    name: 'Password Strength Checker',
    description: 'Check password strength and security',
    path: '/dev-tools/jwt-security/password-strength',
    category: 'dev-tools',
    subcategory: 'jwt-security',
    keywords: ['password', 'strength', 'security', 'check', 'validator'],
  },
  {
    id: 'random-string',
    name: 'Random String Generator',
    description: 'Generate random strings for passwords and tokens',
    path: '/dev-tools/jwt-security/random-string',
    category: 'dev-tools',
    subcategory: 'jwt-security',
    keywords: ['random', 'string', 'generator', 'password', 'token'],
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test regular expressions with live matching',
    path: '/dev-tools/regex-tools/regex-tester',
    category: 'dev-tools',
    subcategory: 'regex-tools',
    keywords: ['regex', 'regular expression', 'test', 'match', 'pattern'],
  },
  {
    id: 'regex-cheatsheet',
    name: 'Regex Cheatsheet',
    description: 'Quick reference for regular expression syntax',
    path: '/dev-tools/regex-tools/regex-cheatsheet',
    category: 'dev-tools',
    subcategory: 'regex-tools',
    keywords: ['regex', 'cheatsheet', 'reference', 'syntax', 'guide'],
  },
  {
    id: 'regex-generator',
    name: 'Regex Generator',
    description: 'Generate regex patterns for common use cases',
    path: '/dev-tools/regex-tools/regex-generator',
    category: 'dev-tools',
    subcategory: 'regex-tools',
    keywords: ['regex', 'generator', 'pattern', 'email', 'url', 'phone'],
  },
  {
    id: 'regex-replace',
    name: 'Regex Replace Tool',
    description: 'Find and replace text using regular expressions',
    path: '/dev-tools/regex-tools/regex-replace',
    category: 'dev-tools',
    subcategory: 'regex-tools',
    keywords: ['regex', 'replace', 'find', 'substitute', 'search'],
  },
  {
    id: 'regex-visualizer',
    name: 'Regex Visualizer',
    description: 'Visualize regex patterns with diagrams',
    path: '/dev-tools/regex-tools/regex-visualizer',
    category: 'dev-tools',
    subcategory: 'regex-tools',
    keywords: ['regex', 'visualizer', 'diagram', 'pattern', 'visual'],
  },
  {
    id: 'regex-html-tags',
    name: 'Regex for HTML Tags',
    description: 'Extract or remove HTML tags using regex',
    path: '/dev-tools/regex-tools/regex-html-tags',
    category: 'dev-tools',
    subcategory: 'regex-tools',
    keywords: ['regex', 'html', 'tags', 'extract', 'remove'],
  },
  {
    id: 'regex-numbers',
    name: 'Regex for Numbers',
    description: 'Extract numbers and numeric patterns',
    path: '/dev-tools/regex-tools/regex-numbers',
    category: 'dev-tools',
    subcategory: 'regex-tools',
    keywords: ['regex', 'numbers', 'numeric', 'extract', 'pattern'],
  },
  {
    id: 'html-minifier',
    name: 'HTML Minifier',
    description: 'Minify HTML by removing whitespace',
    path: '/dev-tools/code-utilities/html-minifier',
    category: 'dev-tools',
    subcategory: 'code-utilities',
    keywords: ['html', 'minify', 'compress', 'optimize'],
  },
  {
    id: 'css-minifier',
    name: 'CSS Minifier',
    description: 'Minify CSS by removing whitespace',
    path: '/dev-tools/code-utilities/css-minifier',
    category: 'dev-tools',
    subcategory: 'code-utilities',
    keywords: ['css', 'minify', 'compress', 'optimize'],
  },
  {
    id: 'js-minifier',
    name: 'JavaScript Minifier',
    description: 'Minify JavaScript code',
    path: '/dev-tools/code-utilities/js-minifier',
    category: 'dev-tools',
    subcategory: 'code-utilities',
    keywords: ['javascript', 'js', 'minify', 'compress', 'optimize'],
  },
  {
    id: 'html-formatter',
    name: 'HTML Formatter',
    description: 'Format and beautify HTML code',
    path: '/dev-tools/code-utilities/html-formatter',
    category: 'dev-tools',
    subcategory: 'code-utilities',
    keywords: ['html', 'format', 'beautify', 'prettify'],
  },
  {
    id: 'css-formatter',
    name: 'CSS Formatter',
    description: 'Format and beautify CSS code',
    path: '/dev-tools/code-utilities/css-formatter',
    category: 'dev-tools',
    subcategory: 'code-utilities',
    keywords: ['css', 'format', 'beautify', 'prettify'],
  },
  {
    id: 'js-formatter',
    name: 'JavaScript Formatter',
    description: 'Format and beautify JavaScript code',
    path: '/dev-tools/code-utilities/js-formatter',
    category: 'dev-tools',
    subcategory: 'code-utilities',
    keywords: ['javascript', 'js', 'format', 'beautify', 'prettify'],
  },
  {
    id: 'html-encoder-decoder',
    name: 'HTML Encoder/Decoder',
    description: 'Encode and decode HTML entities',
    path: '/dev-tools/code-utilities/html-encoder-decoder',
    category: 'dev-tools',
    subcategory: 'code-utilities',
    keywords: ['html', 'encode', 'decode', 'entities', 'escape'],
  },
  {
    id: 'css-to-inline',
    name: 'CSS to Inline Style',
    description: 'Convert CSS to inline style attributes',
    path: '/dev-tools/code-utilities/css-to-inline',
    category: 'dev-tools',
    subcategory: 'code-utilities',
    keywords: ['css', 'inline', 'style', 'convert', 'email'],
  },
  {
    id: 'meta-title-description-preview',
    name: 'Meta Title & Description Preview',
    description: 'Preview how meta tags appear in Google search results',
    path: '/seo-marketing/meta-serp/meta-title-description-preview',
    category: 'seo-marketing',
    subcategory: 'meta-serp',
    keywords: ['meta', 'title', 'description', 'preview', 'seo', 'google'],
  },
  {
    id: 'google-serp-preview',
    name: 'Google SERP Preview',
    description: 'See how your page appears in Google search results',
    path: '/seo-marketing/meta-serp/google-serp-preview',
    category: 'seo-marketing',
    subcategory: 'meta-serp',
    keywords: ['serp', 'google', 'preview', 'search', 'results', 'seo'],
  },
  {
    id: 'facebook-og-preview',
    name: 'Facebook Open Graph Preview',
    description: 'Preview how your link appears on Facebook',
    path: '/seo-marketing/meta-serp/facebook-og-preview',
    category: 'seo-marketing',
    subcategory: 'meta-serp',
    keywords: ['facebook', 'open graph', 'og', 'preview', 'social', 'meta'],
  },
  {
    id: 'twitter-card-preview',
    name: 'Twitter Card Preview',
    description: 'Preview how your link appears on Twitter',
    path: '/seo-marketing/meta-serp/twitter-card-preview',
    category: 'seo-marketing',
    subcategory: 'meta-serp',
    keywords: ['twitter', 'card', 'preview', 'social', 'meta'],
  },
  {
    id: 'character-counter',
    name: 'Character Counter',
    description: 'Count characters in titles and descriptions for SEO',
    path: '/seo-marketing/meta-serp/character-counter',
    category: 'seo-marketing',
    subcategory: 'meta-serp',
    keywords: ['character', 'counter', 'count', 'length', 'seo'],
  },
  {
    id: 'headline-analyzer',
    name: 'Headline Analyzer',
    description: 'Score headline effectiveness and get improvement tips',
    path: '/seo-marketing/meta-serp/headline-analyzer',
    category: 'seo-marketing',
    subcategory: 'meta-serp',
    keywords: ['headline', 'analyzer', 'score', 'title', 'effectiveness'],
  },
  {
    id: 'schema-markup-validator',
    name: 'Schema Markup Validator',
    description: 'Validate structured data for SEO',
    path: '/seo-marketing/meta-serp/schema-markup-validator',
    category: 'seo-marketing',
    subcategory: 'meta-serp',
    keywords: ['schema', 'markup', 'structured data', 'validator', 'seo'],
  },
  {
    id: 'robots-txt-generator',
    name: 'Robots.txt Generator',
    description: 'Create robots.txt file for search engines',
    path: '/seo-marketing/robots-indexing/robots-txt-generator',
    category: 'seo-marketing',
    subcategory: 'robots-indexing',
    keywords: ['robots', 'txt', 'generator', 'seo', 'crawl'],
  },
  {
    id: 'meta-robots-generator',
    name: 'Meta Robots Generator',
    description: 'Generate meta robots tags for pages',
    path: '/seo-marketing/robots-indexing/meta-robots-generator',
    category: 'seo-marketing',
    subcategory: 'robots-indexing',
    keywords: ['meta', 'robots', 'generator', 'noindex', 'nofollow'],
  },
  {
    id: 'noindex-nofollow-checker',
    name: 'Noindex / Nofollow Checker',
    description: 'Verify page indexing rules and directives',
    path: '/seo-marketing/robots-indexing/noindex-nofollow-checker',
    category: 'seo-marketing',
    subcategory: 'robots-indexing',
    keywords: ['noindex', 'nofollow', 'checker', 'meta', 'robots'],
  },
  {
    id: 'canonical-url-generator',
    name: 'Canonical URL Generator',
    description: 'Generate canonical tags for duplicate content',
    path: '/seo-marketing/robots-indexing/canonical-url-generator',
    category: 'seo-marketing',
    subcategory: 'robots-indexing',
    keywords: ['canonical', 'url', 'generator', 'duplicate', 'seo'],
  },
  {
    id: 'sitemap-generator',
    name: 'Sitemap Generator',
    description: 'Build basic XML sitemap for your website',
    path: '/seo-marketing/robots-indexing/sitemap-generator',
    category: 'seo-marketing',
    subcategory: 'robots-indexing',
    keywords: ['sitemap', 'xml', 'generator', 'seo', 'urls'],
  },
  {
    id: 'disallow-path-checker',
    name: 'Disallow Path Checker',
    description: 'Verify if a path is blocked in robots.txt',
    path: '/seo-marketing/robots-indexing/disallow-path-checker',
    category: 'seo-marketing',
    subcategory: 'robots-indexing',
    keywords: ['disallow', 'path', 'checker', 'robots', 'txt'],
  },
  {
    id: 'robots-txt-validator',
    name: 'Robots.txt Syntax Validator',
    description: 'Check robots.txt syntax correctness',
    path: '/seo-marketing/robots-indexing/robots-txt-validator',
    category: 'seo-marketing',
    subcategory: 'robots-indexing',
    keywords: ['robots', 'txt', 'validator', 'syntax', 'check'],
  },
  {
    id: 'utm-builder',
    name: 'UTM Builder',
    description: 'Build UTM-tagged URLs for campaign tracking',
    path: '/seo-marketing/utm-campaign/utm-builder',
    category: 'seo-marketing',
    subcategory: 'utm-campaign',
    keywords: ['utm', 'builder', 'campaign', 'tracking', 'analytics'],
  },
  {
    id: 'campaign-name-generator',
    name: 'Campaign Name Generator',
    description: 'Generate standardized campaign names',
    path: '/seo-marketing/utm-campaign/campaign-name-generator',
    category: 'seo-marketing',
    subcategory: 'utm-campaign',
    keywords: ['campaign', 'name', 'generator', 'utm', 'marketing'],
  },
  {
    id: 'utm-qr-code-generator',
    name: 'UTM QR Code Generator',
    description: 'Generate QR codes for UTM-tagged links',
    path: '/seo-marketing/utm-campaign/utm-qr-code-generator',
    category: 'seo-marketing',
    subcategory: 'utm-campaign',
    keywords: ['utm', 'qr', 'code', 'generator', 'tracking'],
  },
  {
    id: 'utm-shortener',
    name: 'UTM Shortener',
    description: 'Shorten long UTM-tagged URLs',
    path: '/seo-marketing/utm-campaign/utm-shortener',
    category: 'seo-marketing',
    subcategory: 'utm-campaign',
    keywords: ['utm', 'shortener', 'url', 'short', 'link'],
  },
  {
    id: 'utm-validator',
    name: 'UTM Validator',
    description: 'Check if UTM parameters are valid',
    path: '/seo-marketing/utm-campaign/utm-validator',
    category: 'seo-marketing',
    subcategory: 'utm-campaign',
    keywords: ['utm', 'validator', 'check', 'parameters', 'valid'],
  },
  {
    id: 'utm-analytics-tester',
    name: 'UTM Analytics URL Tester',
    description: 'Test UTM tracking in Google Analytics',
    path: '/seo-marketing/utm-campaign/utm-analytics-tester',
    category: 'seo-marketing',
    subcategory: 'utm-campaign',
    keywords: ['utm', 'analytics', 'tester', 'google', 'tracking'],
  },
  {
    id: 'utm-batch-generator',
    name: 'UTM Batch Generator',
    description: 'Generate multiple UTM links at once',
    path: '/seo-marketing/utm-campaign/utm-batch-generator',
    category: 'seo-marketing',
    subcategory: 'utm-campaign',
    keywords: ['utm', 'batch', 'generator', 'multiple', 'bulk'],
  },
  {
    id: 'readability-checker',
    name: 'Readability Checker',
    description: 'Analyze text readability and grade level',
    path: '/seo-marketing/content-writing/readability-checker',
    category: 'seo-marketing',
    subcategory: 'content-writing',
    keywords: ['readability', 'checker', 'flesch', 'grade', 'analysis'],
  },
  {
    id: 'keyword-density-checker',
    name: 'Keyword Density Checker',
    description: 'Check keyword frequency and density',
    path: '/seo-marketing/content-writing/keyword-density-checker',
    category: 'seo-marketing',
    subcategory: 'content-writing',
    keywords: ['keyword', 'density', 'frequency', 'seo', 'checker'],
  },
  {
    id: 'text-case-converter',
    name: 'Text Case Converter',
    description: 'Convert text to upper, lower, title, or sentence case',
    path: '/seo-marketing/content-writing/text-case-converter',
    category: 'seo-marketing',
    subcategory: 'content-writing',
    keywords: ['text', 'case', 'converter', 'upper', 'lower', 'title'],
  },
  {
    id: 'plagiarism-detector',
    name: 'Plagiarism Detector',
    description: 'Check for duplicate content (basic)',
    path: '/seo-marketing/content-writing/plagiarism-detector',
    category: 'seo-marketing',
    subcategory: 'content-writing',
    keywords: ['plagiarism', 'detector', 'duplicate', 'content', 'check'],
  },
  {
    id: 'sentence-splitter',
    name: 'Sentence Splitter',
    description: 'Split paragraphs into individual sentences',
    path: '/seo-marketing/content-writing/sentence-splitter',
    category: 'seo-marketing',
    subcategory: 'content-writing',
    keywords: ['sentence', 'splitter', 'split', 'paragraph', 'text'],
  },
  {
    id: 'word-counter',
    name: 'Word Counter',
    description: 'Count words, characters, and sentences',
    path: '/seo-marketing/content-writing/word-counter',
    category: 'seo-marketing',
    subcategory: 'content-writing',
    keywords: ['word', 'counter', 'count', 'characters', 'sentences'],
  },
  {
    id: 'text-summarizer',
    name: 'Text Summarizer',
    description: 'Generate short summary from text (rule-based)',
    path: '/seo-marketing/content-writing/text-summarizer',
    category: 'seo-marketing',
    subcategory: 'content-writing',
    keywords: ['text', 'summarizer', 'summary', 'shorten', 'extract'],
  },
  {
    id: 'mrr-calculator',
    name: 'MRR Calculator',
    description: 'Calculate monthly recurring revenue for SaaS',
    path: '/calculators/saas-startup/mrr-calculator',
    category: 'calculators',
    subcategory: 'saas-startup',
    keywords: ['mrr', 'monthly', 'recurring', 'revenue', 'saas'],
  },
  {
    id: 'arr-calculator',
    name: 'ARR Calculator',
    description: 'Annual revenue projection calculator',
    path: '/calculators/saas-startup/arr-calculator',
    category: 'calculators',
    subcategory: 'saas-startup',
    keywords: ['arr', 'annual', 'revenue', 'projection', 'saas'],
  },
  {
    id: 'churn-impact-calculator',
    name: 'Churn Impact Calculator',
    description: 'See effect of churn on revenue over time',
    path: '/calculators/saas-startup/churn-impact-calculator',
    category: 'calculators',
    subcategory: 'saas-startup',
    keywords: ['churn', 'impact', 'revenue', 'retention', 'saas'],
  },
  {
    id: 'cac-ltv-calculator',
    name: 'CAC vs LTV Calculator',
    description: 'Compare customer acquisition cost with lifetime value',
    path: '/calculators/saas-startup/cac-ltv-calculator',
    category: 'calculators',
    subcategory: 'saas-startup',
    keywords: ['cac', 'ltv', 'customer', 'acquisition', 'lifetime', 'value'],
  },
  {
    id: 'burn-rate-calculator',
    name: 'Startup Burn Rate Calculator',
    description: 'Track runway and expenses for startups',
    path: '/calculators/saas-startup/burn-rate-calculator',
    category: 'calculators',
    subcategory: 'saas-startup',
    keywords: ['burn', 'rate', 'runway', 'expenses', 'startup'],
  },
  {
    id: 'revenue-growth-calculator',
    name: 'Revenue Growth Calculator',
    description: 'Project revenue growth over time',
    path: '/calculators/saas-startup/revenue-growth-calculator',
    category: 'calculators',
    subcategory: 'saas-startup',
    keywords: ['revenue', 'growth', 'projection', 'forecast'],
  },
  {
    id: 'profit-margin-calculator',
    name: 'Profit Margin Calculator',
    description: 'Calculate gross and net profit margins',
    path: '/calculators/saas-startup/profit-margin-calculator',
    category: 'calculators',
    subcategory: 'saas-startup',
    keywords: ['profit', 'margin', 'gross', 'net', 'revenue'],
  },
  {
    id: 'file-size-calculator',
    name: 'File Size Calculator',
    description: 'Convert bytes, KB, MB, GB, TB',
    path: '/calculators/tech-hosting/file-size-calculator',
    category: 'calculators',
    subcategory: 'tech-hosting',
    keywords: ['file', 'size', 'bytes', 'kb', 'mb', 'gb', 'converter'],
  },
  {
    id: 'bandwidth-calculator',
    name: 'Bandwidth Calculator',
    description: 'Estimate traffic bandwidth usage',
    path: '/calculators/tech-hosting/bandwidth-calculator',
    category: 'calculators',
    subcategory: 'tech-hosting',
    keywords: ['bandwidth', 'traffic', 'usage', 'estimate'],
  },
  {
    id: 'cdn-cost-estimator',
    name: 'CDN Cost Estimator',
    description: 'Estimate costs for static assets delivery',
    path: '/calculators/tech-hosting/cdn-cost-estimator',
    category: 'calculators',
    subcategory: 'tech-hosting',
    keywords: ['cdn', 'cost', 'estimate', 'assets', 'delivery'],
  },
  {
    id: 'image-load-time-calculator',
    name: 'Image Size vs Load Time',
    description: 'Calculate impact of image size on load time',
    path: '/calculators/tech-hosting/image-load-time-calculator',
    category: 'calculators',
    subcategory: 'tech-hosting',
    keywords: ['image', 'size', 'load', 'time', 'performance'],
  },
  {
    id: 'video-size-calculator',
    name: 'Video Size Calculator',
    description: 'Estimate video file size based on parameters',
    path: '/calculators/tech-hosting/video-size-calculator',
    category: 'calculators',
    subcategory: 'tech-hosting',
    keywords: ['video', 'size', 'estimate', 'bitrate', 'duration'],
  },
  {
    id: 'compression-savings-calculator',
    name: 'Compression Savings Calculator',
    description: 'Estimate savings from file compression',
    path: '/calculators/tech-hosting/compression-savings-calculator',
    category: 'calculators',
    subcategory: 'tech-hosting',
    keywords: ['compression', 'savings', 'gzip', 'brotli'],
  },
  {
    id: 'hosting-cost-calculator',
    name: 'Hosting Cost Calculator',
    description: 'Compare hosting plans based on traffic',
    path: '/calculators/tech-hosting/hosting-cost-calculator',
    category: 'calculators',
    subcategory: 'tech-hosting',
    keywords: ['hosting', 'cost', 'compare', 'traffic', 'plans'],
  },
  {
    id: 'keyword-density-calc',
    name: 'Keyword Density Calculator',
    description: 'Measure keyword usage percentage',
    path: '/calculators/seo-calc/keyword-density-calc',
    category: 'calculators',
    subcategory: 'seo-calc',
    keywords: ['keyword', 'density', 'percentage', 'seo'],
  },
  {
    id: 'title-pixel-width-checker',
    name: 'Title Pixel Width Checker',
    description: 'Check pixel width for SERP display',
    path: '/calculators/seo-calc/title-pixel-width-checker',
    category: 'calculators',
    subcategory: 'seo-calc',
    keywords: ['title', 'pixel', 'width', 'serp', 'display'],
  },
  {
    id: 'meta-description-length-checker',
    name: 'Meta Description Length Checker',
    description: 'Validate meta description length',
    path: '/calculators/seo-calc/meta-description-length-checker',
    category: 'calculators',
    subcategory: 'seo-calc',
    keywords: ['meta', 'description', 'length', 'checker', 'seo'],
  },
  {
    id: 'page-speed-score-estimator',
    name: 'Page Speed Score Estimator',
    description: 'Basic page speed score estimation',
    path: '/calculators/seo-calc/page-speed-score-estimator',
    category: 'calculators',
    subcategory: 'seo-calc',
    keywords: ['page', 'speed', 'score', 'performance', 'estimate'],
  },
  {
    id: 'backlink-value-estimator',
    name: 'Backlink Value Estimator',
    description: 'Estimate backlink worth and quality',
    path: '/calculators/seo-calc/backlink-value-estimator',
    category: 'calculators',
    subcategory: 'seo-calc',
    keywords: ['backlink', 'value', 'estimate', 'worth', 'seo'],
  },
  {
    id: 'internal-link-counter',
    name: 'Internal Link Counter',
    description: 'Count internal links per page',
    path: '/calculators/seo-calc/internal-link-counter',
    category: 'calculators',
    subcategory: 'seo-calc',
    keywords: ['internal', 'link', 'counter', 'count', 'seo'],
  },
  {
    id: 'canonical-url-checker',
    name: 'Canonical URL Checker',
    description: 'Verify canonical URLs in HTML',
    path: '/calculators/seo-calc/canonical-url-checker',
    category: 'calculators',
    subcategory: 'seo-calc',
    keywords: ['canonical', 'url', 'checker', 'verify', 'seo'],
  },
  {
    id: 'percentage-calculator',
    name: 'Percentage Calculator',
    description: 'Calculate percentages and ratios',
    path: '/calculators/general-utils/percentage-calculator',
    category: 'calculators',
    subcategory: 'general-utils',
    keywords: ['percentage', 'calculator', 'ratio', 'percent'],
  },
  {
    id: 'time-difference-calculator',
    name: 'Time Difference Calculator',
    description: 'Compute time differences between timestamps',
    path: '/calculators/general-utils/time-difference-calculator',
    category: 'calculators',
    subcategory: 'general-utils',
    keywords: ['time', 'difference', 'calculator', 'duration'],
  },
  {
    id: 'unit-converter',
    name: 'Unit Converter',
    description: 'Convert units (KB/MB/GB, cm/in, etc.)',
    path: '/calculators/general-utils/unit-converter',
    category: 'calculators',
    subcategory: 'general-utils',
    keywords: ['unit', 'converter', 'conversion', 'measurement'],
  },
  {
    id: 'age-calculator',
    name: 'Age Calculator',
    description: 'Compute age from date of birth',
    path: '/calculators/general-utils/age-calculator',
    category: 'calculators',
    subcategory: 'general-utils',
    keywords: ['age', 'calculator', 'dob', 'birthday'],
  },
  {
    id: 'date-calculator',
    name: 'Date Calculator',
    description: 'Calculate days between dates',
    path: '/calculators/general-utils/date-calculator',
    category: 'calculators',
    subcategory: 'general-utils',
    keywords: ['date', 'calculator', 'days', 'between', 'difference'],
  },
  {
    id: 'currency-converter',
    name: 'Currency Converter',
    description: 'Convert currencies with static rates',
    path: '/calculators/general-utils/currency-converter',
    category: 'calculators',
    subcategory: 'general-utils',
    keywords: ['currency', 'converter', 'exchange', 'rate'],
  },
  {
    id: 'random-number-generator',
    name: 'Random Number Generator',
    description: 'Generate random numbers in a range',
    path: '/calculators/general-utils/random-number-generator',
    category: 'calculators',
    subcategory: 'general-utils',
    keywords: ['random', 'number', 'generator', 'range'],
  },
  {
    id: 'color-palette-generator',
    name: 'Color Palette Generator',
    description: 'Generate harmonious color palettes for your designs',
    path: '/design-tools/color-tools/color-palette-generator',
    category: 'design-tools',
    subcategory: 'color-tools',
    keywords: ['color', 'palette', 'generator', 'design', 'harmony'],
  },
  {
    id: 'color-converter',
    name: 'HEX ↔ RGB ↔ HSL Converter',
    description: 'Convert between HEX, RGB, and HSL color codes',
    path: '/design-tools/color-tools/color-converter',
    category: 'design-tools',
    subcategory: 'color-tools',
    keywords: ['hex', 'rgb', 'hsl', 'color', 'converter'],
  },
  {
    id: 'contrast-checker',
    name: 'Contrast Checker',
    description: 'Check WCAG accessibility contrast ratios',
    path: '/design-tools/color-tools/contrast-checker',
    category: 'design-tools',
    subcategory: 'color-tools',
    keywords: ['contrast', 'accessibility', 'wcag', 'a11y', 'checker'],
  },
  {
    id: 'gradient-generator',
    name: 'Gradient Generator',
    description: 'Create beautiful CSS gradients visually',
    path: '/design-tools/color-tools/gradient-generator',
    category: 'design-tools',
    subcategory: 'color-tools',
    keywords: ['gradient', 'css', 'generator', 'linear', 'radial'],
  },
  {
    id: 'random-color-generator',
    name: 'Random Color Generator',
    description: 'Generate random colors with one click',
    path: '/design-tools/color-tools/random-color-generator',
    category: 'design-tools',
    subcategory: 'color-tools',
    keywords: ['random', 'color', 'generator', 'hex', 'rgb'],
  },
  {
    id: 'color-blind-simulator',
    name: 'Color Blind Simulator',
    description: 'Preview colors for colorblind users',
    path: '/design-tools/color-tools/color-blind-simulator',
    category: 'design-tools',
    subcategory: 'color-tools',
    keywords: ['colorblind', 'simulator', 'accessibility', 'deuteranopia', 'protanopia'],
  },
  {
    id: 'palette-exporter',
    name: 'Palette Exporter',
    description: 'Export color palettes in CSS, JSON, or SCSS format',
    path: '/design-tools/color-tools/palette-exporter',
    category: 'design-tools',
    subcategory: 'color-tools',
    keywords: ['palette', 'export', 'css', 'json', 'scss'],
  },
];

export function getToolsByCategory(categoryId: string): Tool[] {
  return TOOLS.filter((tool) => tool.category === categoryId);
}

export function getToolsBySubcategory(subcategoryId: string): Tool[] {
  return TOOLS.filter((tool) => tool.subcategory === subcategoryId);
}

export function getToolById(toolId: string): Tool | undefined {
  return TOOLS.find((tool) => tool.id === toolId);
}

export function getCategoryById(categoryId: string): Category | undefined {
  return CATEGORIES[categoryId];
}

export function getSubcategoryById(
  categoryId: string,
  subcategoryId: string
): Subcategory | undefined {
  const category = CATEGORIES[categoryId];
  return category?.subcategories.find((sub) => sub.id === subcategoryId);
}
