import {
  IconJson,
  IconFileCode,
  IconLock,
  IconHash,
  IconRegex,
  IconCode,
  IconSearch,
  IconRobot,
  IconChartBar,
  IconPencil,
  IconCurrencyDollar,
  IconServer,
  IconTrendingUp,
  IconCalculator,
  IconPalette,
  IconFileTypeDocx,
  IconTransform,
  IconFileText,
  IconArrowsMinimize,
  IconCheck,
  IconArrowsLeftRight,
  IconBrandGoogle,
  IconBrandFacebook,
  IconBrandTwitter,
  IconSitemap,
  IconFileSettings,
  IconQrcode,
  IconLink,
  IconAB,
  IconClock,
  IconRuler,
  IconCalendar,
  IconPercentage,
  IconWorld,
  IconDroplet,
  IconColorPicker,
  IconGradienter,
  IconEye,
  IconContrast,
  IconDatabase,
  IconKey,
  IconShieldLock,
  IconBinary,
  IconNumbers,
  IconReplace,
  IconEyeCheck,
  IconCodeDots,
  IconBraces,
  IconBrackets,
  IconChevronDown,
} from '@tabler/icons-react';

export const TOOL_ICONS: Record<string, any> = {
  // JSON Tools
  'json-formatter': IconJson,
  'json-minifier': IconArrowsMinimize,
  'json-validator': IconCheck,
  'json-to-yaml': IconFileTypeDocx,
  'yaml-to-json': IconJson,
  'json-to-toml': IconFileCode,
  'csv-to-json': IconArrowsLeftRight,
  'json-diff': IconArrowsLeftRight,

  // JWT & Security
  'jwt-decoder': IconKey,
  'jwt-expiry-checker': IconClock,
  'base64-encode-decode': IconBinary,
  'md5-hash': IconHash,
  'sha256-hash': IconShieldLock,
  'password-strength': IconLock,
  'random-string': IconAB,

  // Regex Tools
  'regex-tester': IconRegex,
  'regex-generator': IconCodeDots,
  'regex-cheatsheet': IconFileText,
  'regex-replace': IconReplace,
  'regex-html-tags': IconBraces,
  'regex-numbers': IconNumbers,
  'regex-visualizer': IconEyeCheck,

  // Code Utilities
  'html-formatter': IconCode,
  'html-minifier': IconArrowsMinimize,
  'css-formatter': IconCode,
  'css-minifier': IconArrowsMinimize,
  'js-formatter': IconCode,
  'js-minifier': IconArrowsMinimize,

  // SEO - Meta & SERP
  'google-serp-preview': IconBrandGoogle,
  'meta-title-description-preview': IconFileText,
  'facebook-og-preview': IconBrandFacebook,
  'twitter-card-preview': IconBrandTwitter,
  'schema-markup-validator': IconCheck,
  'headline-analyzer': IconPencil,
  'character-counter': IconAB,

  // SEO - Robots & Indexing
  'robots-txt-generator': IconRobot,
  'robots-txt-validator': IconCheck,
  'sitemap-generator': IconSitemap,
  'canonical-url-generator': IconLink,
  'meta-robots-generator': IconFileSettings,
  'noindex-nofollow-checker': IconEyeCheck,
  'disallow-path-checker': IconSearch,

  // SEO - UTM & Campaign
  'utm-builder': IconLink,
  'utm-validator': IconCheck,
  'utm-qr-code-generator': IconQrcode,
  'utm-batch-generator': IconDatabase,
  'utm-shortener': IconArrowsMinimize,
  'utm-analytics-tester': IconChartBar,
  'campaign-name-generator': IconPencil,

  // SEO - Content & Writing
  'word-counter': IconAB,
  'readability-checker': IconEyeCheck,
  'keyword-density-checker': IconSearch,
  'plagiarism-detector': IconSearch,
  'text-summarizer': IconArrowsMinimize,
  'sentence-splitter': IconArrowsLeftRight,
  'text-case-converter': IconTransform,

  // Calculators - SaaS & Startup
  'mrr-calculator': IconCurrencyDollar,
  'arr-calculator': IconTrendingUp,
  'churn-rate-calculator': IconChartBar,
  'cac-calculator': IconCurrencyDollar,
  'ltv-calculator': IconTrendingUp,
  'revenue-growth-calculator': IconChartBar,
  'churn-impact-calculator': IconChartBar,
  'cac-ltv-calculator': IconTrendingUp,
  'burn-rate-calculator': IconCurrencyDollar,
  'profit-margin-calculator': IconPercentage,

  // Calculators - Tech & Hosting
  'file-size-calculator': IconServer,
  'bandwidth-calculator': IconServer,
  'cdn-cost-estimator': IconCurrencyDollar,
  'hosting-cost-calculator': IconServer,
  'image-load-time-calculator': IconClock,
  'video-size-calculator': IconServer,
  'compression-savings-calculator': IconServer,

  // Calculators - SEO
  'keyword-density-calculator': IconSearch,
  'title-width-calculator': IconRuler,
  'backlink-value-calculator': IconTrendingUp,

  // Calculators - General
  'percentage-calculator': IconPercentage,
  'time-difference-calculator': IconClock,
  'date-calculator': IconCalendar,
  'age-calculator': IconCalendar,
  'unit-converter': IconRuler,
  'currency-converter': IconCurrencyDollar,

  // Design Tools
  'color-converter': IconColorPicker,
  'color-palette-generator': IconPalette,
  'gradient-generator': IconGradienter,
  'random-color-generator': IconDroplet,
  'color-blind-simulator': IconEye,
  'contrast-checker': IconContrast,
  'palette-exporter': IconDatabase,
};

// Top 12 tools for each category (most important/popular)
export const TOP_TOOLS_BY_CATEGORY: Record<string, string[]> = {
  'dev-tools': [
    'json-formatter',
    'json-validator',
    'jwt-decoder',
    'base64-encode-decode',
    'regex-tester',
    'json-minifier',
    'md5-hash',
    'sha256-hash',
    'html-formatter',
    'css-minifier',
    'js-formatter',
    'json-to-yaml',
  ],
  'seo-marketing': [
    'google-serp-preview',
    'meta-title-description-preview',
    'robots-txt-generator',
    'sitemap-generator',
    'utm-builder',
    'facebook-og-preview',
    'twitter-card-preview',
    'keyword-density-checker',
    'word-counter',
    'readability-checker',
    'canonical-url-generator',
    'schema-markup-validator',
  ],
  'calculators': [
    'mrr-calculator',
    'arr-calculator',
    'percentage-calculator',
    'date-calculator',
    'time-difference-calculator',
    'currency-converter',
    'unit-converter',
    'churn-rate-calculator',
    'cac-calculator',
    'ltv-calculator',
    'bandwidth-calculator',
    'age-calculator',
  ],
  'design-tools': [
    'color-converter',
    'color-palette-generator',
    'gradient-generator',
    'random-color-generator',
    'color-blind-simulator',
    'contrast-checker',
    'palette-exporter',
  ],
};
